package com.ssvtech.jalforce1.Utility;

public class MessageUtility {

    public static String DAILY_ROUTE_SUMMARY_RECORD_NOT_THERE = "DAILY_ROUTE_SUMMARY_RECORD_NOT_THERE";
    public static String DAILY_DELIVERY_EXCEDDING_LOADED_CANS = "DAILY_DELIVERY_EXCEDDING_LOADED_CANS";
    public static String DAILY_DELIVERY_SUCCESSFUL_TO_CUSTOMER = "DAILY_DELIVERY_SUCCESSFUL_TO_CUSTOMER";
    public static String DAILY_DELIVERY_RETURN_CANS_EXCEDDING_PENDING_CANS = "DAILY_DELIVERY_RETURN_CANS_EXCEDDING_PENDING_CANS";
    public static String DAILY_ROUTE_SUMMARY_MULTIPLE_RECORDS_FOUNDED = "DAILY_ROUTE_SUMMARY_MULTIPLE_RECORDS_FOUNDED";
    public static String DAILY_ROUTE_TRIP_HAS_ALREADY_ENDED = "DAILY_ROUTE_TRIP_HAS_ALREADY_ENDED";

    public static String DAILY_ROUTE_TRIP_STARTED_SUCESSFULLY = "DAILY_ROUTE_TRIP_STARTED_SUCESSFULLY";
    public static String DAILY_ROUTE_TRIP_ENDED_SUCESSFULLY = "DAILY_ROUTE_TRIP_ENDED_SUCESSFULLY";


   // public static String APPLICATION_NAME = "Aquademo";
   public static String APPLICATION_NAME = "Users";


}
